import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import ColorInput from "../components/ColorInput";
import FinanceInput from "../components/FinanceStatus";

export default function Home() {
  const [loginInput, setLoginInput] = useState("");
  const [registerInput, setRegisterInput] = useState("");

  const [isLogged, setLogged] = useState(false);
  const [isFound, setIsFound] = useState(true);

  const [isRegister, setRegister] = useState(false);

  const loginHandler = async () => {
    const res = await fetch("/api/login", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ name: loginInput }),
    });
  };
  const registerHandler = async () => {
    console.log("registerInput", registerInput);
    const res = await fetch("/api/register", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ name: registerInput }),
    });
    console.log(res);
  };
  let title;
  if (isRegister) title = "Регистрация";
  else if (!isRegister) title = "Вход";
  else title = "Finance calculator";
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container flex-col h-screen flex-center">
        <div className="mb-10 text-5xl font-bold text-blue">{title}</div>

        {!isLogged && !isRegister && (
          <>
            <ColorInput
              labelName="Име"
              type="text"
              state={isFound ? "" : "wrong"}
              input={loginInput}
              setInput={(e) => setLoginInput(e.target.value)}
              onClick={loginHandler}
            />
            <div
              className="mt-10 underline cursor-pointer"
              onClick={() => setRegister(true)}
            >
              Регистрация
            </div>
          </>
        )}
        {!isLogged && isRegister && (
          <>
            <ColorInput
              labelName="Име"
              type="text"
              state={isFound ? "" : "wrong"}
              input={registerInput}
              setInput={(e) => setRegisterInput(e.target.value)}
              onClick={registerHandler}
            />
            <div
              className="mt-10 underline cursor-pointer"
              onClick={() => setRegister(false)}
            >
              Вход
            </div>
          </>
        )}
        {isLogged && <FinanceInput />}
      </main>
    </div>
  );
}
